Release prep: Documentation, Changelog, tests, ect.
ploperations/ploperations-github pull request #2
Opened 2019-11-08 01:09 UTC by suckatrash

Release prep.  Went through steps outlined in [repo_standards](https://github.com/ploperations/repo_standards)

2019-11-08 16:17 UTC, suckatrash commented
@genebean I don't know why these tests are failing, they're pretty standard and work pretty much everywhere else. 

While I was looking into this I realized that the module has a [dependency](https://github.com/ploperations/ploperations-github/blob/master/manifests/listener.pp#L7-L8) on an `apache` class, but not the one form the forge.  Seems we have one in our control repo in the `dist` folder.

I'm sort of questioning whether we should publish this on the forge at this point, thoughts?

2019-11-08 18:05 UTC, genebean commented
your spec file has a .pp extension instead of a .rb - that's why its busted

2019-11-08 18:06 UTC, genebean commented
we should hold releasing to the forge for now.

2019-11-08 22:01 UTC, genebean commented on README.md
Will you add a block right here until we fix the private dependency:

```markdown

> NOTE: this module currently uses a private fork of the apache module. We are working to migrate it to the normal version of apache and plan to release it on the Forge after that.
```

2019-11-08 22:03 UTC, genebean requested changes
When doing docs for puppet strings both a description and a summary are needed... even if they are the same. So... the top of a class file should look kinda like this:

```markdown
# Defined type that creates a github mirror for a given repo
#
# @summary Defined type that creates a github mirror for a given repo
#
# @param ensure
```

2019-11-08 22:07 UTC, genebean commented
Have you tested to see if this will work with the public apache module? I saw there is no version in the fixtures file

2019-11-08 22:10 UTC, suckatrash commented
Wow.. ok, the tests are working much better now thanks @genebean 
![ape](https://user-images.githubusercontent.com/14116564/68512201-9b90dc00-022c-11ea-89dd-c0dabe22e53b.gif)

Nope, I sort of assumed there would be problems with the public module but I can try it out.

2019-11-08 22:35 UTC, suckatrash commented
Looks like the differences in the `apache` classes have surfaced in these tests.

2019-11-09 00:29 UTC, genebean commented
Looks like your fixtures need https://forge.puppet.com/puppetlabs/yumrepo_core as that’s bundled with agents but not the puppet gem

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

2019-11-09 00:54 UTC, genebean commented
Bummer, real failures 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

2019-11-14 22:12 UTC, hsnodgrass commented
@genebean @suckatrash Tests passed. Once this is merged I can add this repo to the control repo's Puppetfile.

2019-11-15 15:42 UTC, hsnodgrass commented
@genebean I've update the apache version to use a range.

2019-11-15 21:52 UTC, genebean approved these changes

2019-11-15 21:53 UTC, merged